apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: showcase-java-web-app
metadata:
  namespace: csnr-devops-lab-deploy
objects:
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations: {}
    creationTimestamp: null
    labels: {}
    name: showcase-java-web-app
  spec:
    minReadySeconds: 300
    replicas: 3
    selector:
      deploymentconfig: showcase-java-web-app
    strategy:
      activeDeadlineSeconds: 21600
      rollingParams:
        intervalSeconds: 1
        maxSurge: 3
        maxUnavailable: 1
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        annotations: {}
        creationTimestamp: null
        labels:
          deploymentconfig: showcase-java-web-app
      spec:
        containers:
        - env:
          - name: OPENSHIFT_KUBE_PING_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: OPENSHIFT_KUBE_PING_LABELS
            value: deploymentconfig=showcase-java-web-app
          - name: CATALINA_OPTS
            value: -Djava.security.egd=file:/dev/./urandom
          image: docker-registry.default.svc:5000/csnr-devops-lab-deploy/showcase-java-web-app-final:latest
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command:
                - kill
                - "-15"
                - "1"
          name: showcase-java-web-app
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 7070
            name: jolokia
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /info
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 30
            periodSeconds: 2
            successThreshold: 3
            timeoutSeconds: 2
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 192Mi
          terminationGracePeriodSeconds: 120
          volumeMounts:
          - mountPath: /usr/local/tomcat/logs
            name: access-logs
        - command:
          - /usr/local/tomcat/filebeat/filebeat
          - run
          - --e
          - -c
          - /usr/local/tomcat/conf/filebeat.yml
          - -E
          - output.console.enabled=false
          - -E
          - output.elasticsearch.hosts=[https://security-master:9200]
          - -E
          - output.elasticsearch.username=elastic
          - -E
          - output.elasticsearch.password=cEFtS5H5Hxv7MNotplorGk
          - -E
          - output.elasticsearch.ssl.verification_mode=none
          image: ' '
          imagePullPolicy: Always
          name: filebeat
          volumeMounts:
          - mountPath: /usr/local/tomcat/logs
            name: access-logs
        - command:
          - /usr/local/tomcat/metricbeat/metricbeat
          - run
          - --e
          - -c
          - /usr/local/tomcat/conf/metricbeat.yml
          - -E
          - output.console.enabled=false
          - -E
          - output.elasticsearch.hosts=[https://security-master:9200]
          - -E
          - output.elasticsearch.username=elastic
          - -E
          - output.elasticsearch.password=cEFtS5H5Hxv7MNotplorGk
          - -E
          - output.elasticsearch.ssl.verification_mode=none
          image: ' '
          imagePullPolicy: Always
          name: metricbeat
        initContainers:
        - command:
          - cp
          - /usr/local/tomcat/conf/filebeat.yml
          - /mnt/conf/
          image: ' '
          name: copy-filebeat-conf
          volumeMounts:
          - mountPath: /mnt/conf
            name: conf
        serviceAccountName: showcase-java-web-app
        volumes:
        - emptyDir: {}
          name: access-logs
        - emptyDir: {}
          name: conf
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - showcase-java-web-app
        - copy-filebeat-conf
        - filebeat
        - metricbeat
        from:
          kind: ImageStreamTag
          name: showcase-java-web-app-final:latest
          namespace: csnr-devops-lab-deploy
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
- apiVersion: v1
  kind: Service
  metadata:
    annotations: {}
    creationTimestamp: null
    labels: {}
    name: showcase-java-web-app
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deploymentconfig: showcase-java-web-app
  status:
    loadBalancer: {}
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    creationTimestamp: null
    labels: {}
    name: showcase-java-web-app
  spec:
    host: ""
    port:
      targetPort: 8080-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: showcase-java-web-app
      weight: 100
  status:
    ingress: null
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: null
    name: showcase-java-web-app
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: showcase-java-web-app
  rules:
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - get
    - watch
    - list
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    creationTimestamp: null
    name: showcase-java-web-app
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: showcase-java-web-app
  subjects:
  - kind: ServiceAccount
    name: showcase-java-web-app
